# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- node-app-development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      Default
    steps:
    - script: docker build -t shahenvaz7/nodeapp:'$(Build.BuildId)' .
    - script: docker push shahenvaz7/nodeapp:'$(Build.BuildId)'
