apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
spec:
    containers:
    - name: hello
      image: nginx
      command: ['sh', '-c', 'echo "Hellow, Kubernetes!" && sleep 3600']
    restartPolicy: OnFailure
